package com.blogspot.aptgetmoo.dhjclient.finder;

import java.io.IOException;

public interface IResultPage {
	/**
	 * @return Search page URL
	 */
	String getBaseUrl();

	/**
	 * @return URL with parameters
	 */
	String getUrl();

	/**
	 * @return HTML page generated by the search
	 * @throws IOException On any IO errors while fetching the page
	 */
	String fetchHtml() throws IOException;

	/**
	 * Set fetch parameters
	 *
	 * @param pKeyword	Keyword for items to fetch
	 * @param pType		Item type
	 * @param pPage		Page number
	 */
	void setFetchParameters(String pKeyword, String pType, int pPage);
}
